# ── Terraform Backend ─────────────────────────────────────────────────────────
# AUTO-GENERATED by tf.sh — do not edit manually.
# Source: terraform_backend.type from the active YAML config.
#
# SAFETY: terraform_backend is read-only metadata. Preconditions in
# backend_safety.tf prevent managing backend resources from non-bootstrap configs.

terraform {
  backend "azurerm" {}
}
